version: "3"

# docker-compose --profile init up

# networks:
#   grafana:
#   prometheus:
#   loki:

services:
  init-grafana:
    profiles:
      - init
    image: ubuntu
    user: root
    command: chown -R 472:0 /var/lib/grafana
    volumes:
      - ./grafana/data:/var/lib/grafana

  init-loki:
    profiles:
      - init
    image: ubuntu
    user: root
    command: chown -R 10001:10001 /data/loki
    volumes:
      - ./loki/data:/data/loki

  init-prometheus:
    profiles:
      - init
    image: ubuntu
    user: root
    command: chown -R 65534:65534 /prometheus
    volumes:
      - ./prometheus/data:/prometheus

  grafana:
    image: grafana/grafana
    restart: unless-stopped
    environment:
      - TC=UTC
      # - GF_SECURITY_ADMIN_USER=***
      # - GF_SECURITY_ADMIN_EMAIL=***
      # - GF_SECURITY_ADMIN_PASSWORD=***

      # - GF_ANALYTICS_REPORTING_ENABLED=false
      - GF_ANALYTICS_CHECK_FOR_UPDATES=true
      - GF_ANALYTICS_CHECK_FOR_PLUGIN_UPDATES=true
      # - GF_SMTP_ENABLED=true

      # - GF_SMTP_HOST=***
      # - GF_SMTP_USER=***
      # - GF_SMTP_PASSWORD=***
    ports:
      - 3000:3000
    # networks:
    #   - prometheus
    volumes:
      # - /etc/timezone:/etc/timezone:ro
      # - /etc/localtime:/etc/localtime:ro
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
      - ./grafana/data:/var/lib/grafana

  # loki:
  #   image: grafana/loki
  #   restart: unless-stopped
  #   environment:
  #     - TC=UTC
  #   command:
  #     - --config.file=/etc/loki/loki.yaml
  #     - --log.level=debug
  #   ports:
  #     - 3100:3100
  #     - 9096:9096
  #     - 7946:7946
  #   volumes:
  #     # - /etc/timezone:/etc/timezone:ro
  #     # - /etc/localtime:/etc/localtime:ro
  #     - ./loki/loki.yaml:/etc/loki/loki.yaml:ro
  #     - ./loki/data:/data/loki

  prometheus:
    image: prom/prometheus
    restart: unless-stopped
    # userns_mode: 'host'
    environment:
      - TC=UTC
    volumes:
      # - /etc/timezone:/etc/timezone:ro
      # - /etc/localtime:/etc/localtime:ro
      - ./prometheus/prometheus.yaml:/etc/prometheus/prometheus.yml:ro
      - ./prometheus/data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--log.level=debug'
    ports:
      - 9090:9090
    # networks:
    #   - prometheus