logs:
  configs:
  - name: docker-logs
    clients:
      - url: http://${LOKI_HOST}/loki/api/v1/push
    positions:
      filename: /tmp/positions.yaml
    scrape_configs:
    - job_name: integrations/docker
      docker_sd_configs:
        - host: unix:///var/run/docker.sock
          refresh_interval: 5s
      relabel_configs:
      - action: replace
        replacement: integrations/docker
        target_label: job
      - action: replace
        replacement: 'update-me' # VM name
        target_label: instance
      - source_labels:
          - __meta_docker_container_name
        regex: '/(.*)'
        target_label: container
      - source_labels: 
          - __meta_docker_container_log_stream
        target_label: stream