integrations:
  # metrics:
  #   autoscrape:
  #     enable: true
  agent:
    instance: foo-agent
  node_exporter:
    instance: foo-node_exporter
    rootfs_path: /host/root
    sysfs_path: /host/sys
    procfs_path: /host/proc
    udev_data_path: /host/root/run/udev/data
    # set_collectors:
    #   - cpu
    #   - diskstats

server:
  log_level: debug

metrics:
  wal_directory: /tmp/agent
  global:
    scrape_interval: 60s
    scrape_timeout: 5s
    remote_write:
      - url: http://dockers.lan:9090/api/v1/push
      # - url: http://nas.lan:9090/api/v1/push
#      - url: http://host.docker.internal:9090/api/v1/push
  configs:
  - name: default
    scrape_configs:
      - job_name: agent-localhost-node-exporter
        static_configs:
          - targets: ['dockers.lan:9100']

# instance: foo
# extra_labels:
#   [ foo: bar]